# Atividade 1 — NumPy

Exercícios de criação de arrays e matrizes com NumPy, usando `ndim`, `shape` e `mean`.

In [1]:
import numpy as np

## 1 - Crie um array com 20 elementos e uma dimensão. Printe ele.

In [2]:
array = np.arange(1, 21)
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


## 2 - Faça a média desse array.

In [3]:
media = array.mean()
print("Média do array:", media)

Média do array: 10.5


## 3 - Crie uma matriz com 10 colunas e 20 linhas.

In [4]:
matriz = np.random.randint(0, 100, size=(20, 10))
print(matriz)

[[89 39 48 55 59 59 33 81 72 37]
 [36  8  8 48 92 36 20 81 41 14]
 [ 4 12 91 45 76 16 77 28 93 22]
 [77 23 75 88 72 57 39 94 18 12]
 [ 7 70 20  5 43 10 84 30 96 74]
 [79 97 36 30 67 53 52 33 99 67]
 [ 0 77 77 25 33 39 53 68 65  9]
 [62 73 71 76 20 47 51 64  0 57]
 [88 33 73 82 69 50 40 73 69 66]
 [16 37 26 48 57 69 28 16 74 18]
 [98 65 95 60 68 61 21 42 89 90]
 [49 62  9 79 22 89 91 61 36 45]
 [37  4 19  8 50 72 17 36 80 61]
 [86 64  7 31 50 44 57 69 11 51]
 [51 40 71 47 81 82  0 47  0 22]
 [44 42 71 94 52 26 74 69 88  0]
 [32 94  9 94 83 88 97 72 25 74]
 [14 62  9 90 15 58 30 57 21 18]
 [65 85  9 83 63 56 63 58 95 84]
 [57 78 85 74 53 36 49 36 44 38]]


## 4 - Qual o shape da matriz?

In [5]:
print("Shape da matriz:", matriz.shape)

Shape da matriz: (20, 10)


A matriz tem **20 linhas** e **10 colunas**, por isso o shape é `(20, 10)`.

## 5 - Utilize os comandos ndim, shape, mean.

In [6]:
print("=== Array ===")
print("ndim :", array.ndim)
print("shape:", array.shape)
print("mean :", array.mean())

print()
print("=== Matriz ===")
print("ndim :", matriz.ndim)
print("shape:", matriz.shape)
print("mean :", matriz.mean())

=== Array ===
ndim : 1
shape: (20,)
mean : 10.5

=== Matriz ===
ndim : 2
shape: (20, 10)
mean : 51.83


- `ndim` → número de dimensões (o array tem 1, a matriz tem 2)
- `shape` → tamanho de cada dimensão
- `mean` → média de todos os elementos